apiVersion: v1
kind: Namespace
metadata:
  name: fishy-site
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: fishy-gh-token
  namespace: fishy-site
spec:
  encryptedData:
    identity: AgApD/1dtqvvKKQZmEGXnLYbsTot50lDCoKPaYjAvOrT5tc/WS0LJXjFtZG5wAhPJxZv7c+xFj1EhSrdcXsnVNASZ7dXX/1mLwZTePK/GGuU5KD5qdH87919C6u83gpZ6bwHDwaCu/QcD56BC3/LDOkZcJlI48oHDncFHWCmSsSndM4K8giZNibuJskR0F6HsofpzMIK3BiKb9gUYJolsA77P0o8yH/fAppCVzk0WppLLpOs1JnMA/VKJJN3ApA/7kutRQ34EThIodYSEC7OMbM7YFbCP1XHJmama43jvavnX/kXQbcOqJUOAcenGRdTk1vJJ5qfea93lkMJF3UB909gsmk9SWSgKiIpVBnZO/d58PrtzFKdDNSF35ZBwzj1uP/jXKlPu8R2Et2DN8jVSruZZCguAwkEgsFE2XBYVwRg6rInY/2EjbHn3F8DY9/29Fx9REZHlsgEMdq5cnOL3ByyyVoVA6jzH5odW3IzMEvB4ffW68/cETCUZe49CI0uZ1ghSMT8eANHfKg+aTpAdrYCZSwYIqZrVTPvxZmHpHIPc+AbrcrZtv6KqT9IpikQwQwi0I6eublt29RmKBBpVABnDXRHiSyPgxgf++6Nms9uCZlPLvYAdfY1njXibV+Mm1T/M9pe85i8l9sX++blRBmF8ZcTVqcAmwi/WcMBCGkG/bgG2zcs9HQ4yR8KmCDiHjY9qjDnDD5Rw23prvGlv9/ZLMz9fsw/T8LtbVo1+vIfZolnnCH9CB38AvoISVTkJ7rV/ZMGDjUh60/Bo7o3cxiTQDBzpDsKnkS4J4ZOB7lvYZ3zsfl3gEmBhmBIlvDyhQ5wmxHy5w7CrMh4gUq++9FZQ7tXHxhgV+1cG4DMb3KgUHA3iIt77L1Vu9/UO54T+La2OZfE2V34Zb2pWmPJyYJK9OsZya9sMK7cjxeOlzwpQhi2+7U9prkL8nuegtyI7qoRq6sw6gPC6f9CLhqWGje+5+Laxvmq2XQsP0FJaBGsa9cfy7wwSEdOHBFsDMaymkrNcSn6MAYUwyBvH0soymnBoPhLuEKvKy0RiI89lXiKoPAWhGj6Wf8T2xNycbmiAB8UHvS3cr53RvDzgs1AJeXuWIAPZwVN1/uRGE5pEI82UjCWHjgSfWGoTqySRA2SteO2obg344FZdqB94b4ReZyxctX7e18nsBCxuUFc+3moFuZDktDtXzdH7YQv7CXYyBusjgOfJtCSbmluNKlBPC5QrTCZdKZ+RQ1bxJU=
    known_hosts: AgCo/foILPKcyPtMBRhRa0kD5DxMa3E0+OXz2huIpg1BiJXSen4jd37aE5SzEqfzCvR/CivBRpBZLI1kZho38vHoi7dLMv1tki/wS53Tgzo29eta1fLP47r1HQNwcsoT8OpVhrLNrnWQTX6wkvbrpO5nRQ1MqnLPkIcrqJqoZUui3xpPRzoQmLRO/bojHTLELqSgioDBhX7vmEZ6n7n4A7UQDSaBLx1IqYoqXolgcQU/wCDvZoLaSfFQgKI6s+JxcwHroKeu21sDp7SJ0SSHIB6QxnYp34GwEs4fedSorx2+665j9m+TSzacvFQPnxt2ZQnWmYpkrCnqu74rs+kWhMV6jO0NnWS4QVA4/n/4otncYpmRDbPHMKV2R8YOu8rg8EA6WVMMZ2L2qCow9fTX66ZXST/mrvwjZ3UJSZMu9qVzvlB1caRyhNc7KmA/tWNFBP34txgnPJ4jS8DzuikXIBR+2+F22HZeW6tLa6vEVqjbqKabWwl1oQhEeqW9cXvY5BIS42dsUwGOpkAvuiSVT0g/+rermqfes7PlPvDYU61gSSs/7EKXyxcMMMhHTux1B1wWswI5mGnrUmgCsws6wBeabUDSGgN61JjE7Uj5MGgruQNgOklKwcuFszNaeqX2OTKiDk0pdGTXYJF5mzIwHjSBXMCgakK4/+eO2DMM5EbpGJz5To5Y4ETcSe9Yf8L9ygDn4YhDRAo/nmkcSUDjFA4clQCCVPW3iT3PzeQ1PS8z+kV4WQbHNEYImQVgPyY6JFxJmTUu5XDIzoWLxgndBkqcmv/hgFFAMi5SnP5CX2NZgVK2YRm+y7e7dKFVEXRt4G1DxRADULlk6ev7kBMx0O7T6RYn9tOHOIi3VtkKB/g3Kip1va0vO6v8gk6E7UuSrNKqOxbQw+cY5wD51lon/YdrYQoONL79bkRtOrRD/K5hQK0uh7B0yXGgXB85uBtmEYAP09LtzCc26LBa4ph1nHHYw5Ah35iSS2JuherZL/PunruYh+uxrBcX087Lo05LwtQBvWCYT7quA+T27IPC7jHTi5lsTMQ7T/2g0hleLiiXYOcIkABOkFIiIGx4w2h6pA/czNmHn3I6RvSEOLLrH9fpUGvSruUCcyiOoxAyeUE+KN+B9kv80tf1tpEJX/hyDHihjVJYxX4OvlZXF5qLXwSQStO1Yc9BHLTnsrLq8PNhUnxOGIFi6mxOsjUEc2pRnJF3VJM0vDXj4AKsrzeDlrS96m7K7QRyhfYBWKEnFePWrY2B2IJ/6CHdYBLw4tfTfJthZFxvxg4rPgzUlI2r5PNTK80QIr455jnskWx4jQU2L6Pin14JjMNW77NqoWU++In4Od75PaRkjxky/CH4p54ylh+ZGCrORqxr+qYY+1bJwZ3CZTVjQcPHS0xzwaXIQPInhlrl5Zrsq/H2JIJ2Yf3OA//gykjKpJzaM0wX2vnJLe0Ig56116mk+52ReeXuVZJq+812XS0MTIvsQfernvqxkgsKpqGCPvZOp/Y+avL4bwaLbDxy+PLeZ6Yhrek0cCW79YQ6whFY3+tU5YXQ5DiDc3KgTaB4Hv1nydJiD95diB9dAJqcX69j/NFDLuT7VIrCS5b+UT/3zCKoE4VMkejonbWY7p8kTb76InI3x0bCz4sz1Y1Af1sDfXXSS1E4sRXZCMY2U7qSBQG0nZA5FP8s08cFcX+/dYQU/QoLzpfr5K3GC1pRjJf4xFatATzdrtRnA7l1jCYmYCKXVsGSwUkVpJzr6S9EM3dgym87euL47Pus03Ll+I20J/uVxQhX0Ka8Z6nIc0OEL8oOgcg=
  template:
    metadata:
      creationTimestamp: null
      name: fishy-gh-token
      namespace: fishy-site
    type: Opaque
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: fish-site
  namespace: fishy-site
spec:
  url: ssh://git@github.com:HowManyFish/FishySite.git
  interval: 5m
  secretRef:
    name: fishy-gh-token
  ref:
    branch: main
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: fishy-site
  namespace: fishy-site
spec:
  interval: 10m
  prune: true
  sourceRef:
    kind: GitRepository
    name: nzdev-org-homepage
  path: ./deploy
