apiVersion: v1
kind: Namespace
metadata:
  name: bitwarden
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: github-bitwarden-token
  namespace: bitwarden
spec:
  encryptedData:
    password: AgBblnM5mxQDgqJm1NpwC7O1h/C05yUQrpQFQO/nmjHZJ0shFbfcBKk2nrGlC4x0VclJBnNtYy5Q+w1B1ow8dHE+Qdik5ZPLc9FPIDtx74xSsPuWPfjMIK2ise1SerUTusEZ1H31tpmo4i+PbY/lAl1ocS9WG52Ez5O6rguO2/Irxg1AE52dClfErCOdA1SWlaGDQYB2/sUqrhjDqOWGFrCI8ZjezfoHZsl4lVMQDie58T+a4ITmMtq9EDRexmZUcIPHcyBeTOYaAzKhtGYei3QfHgwtQ+ibnF0LMcf4b5SbY81akfqLlyWVWwnh+pPatjfjlS0cNnkpI5h1AXPoXqpuLePE7cvSZBpx1MFaoos8W55Sxu3ZJtaY11lfx4sXJ+UwFlfNZb31NqwpAAwPOCgwAdnsklMNV2yYyRVpLmGccj9RDLGSB1YaZxBqR1p50+e26Y2J/e4MA6BbwN4Rq2v8ecrZh//R9PNjmtivc1fUf1ao51pqxks7UtxQlzG8cPBKd648Jw6Z/fMKg1o+qpksr1EwCP8CdozzvgkrkH2ge9fsbh0Vl3UoTpb5PPpR8iy0cZFxukCB8wWmiWJOGSJuj8BMy6yaOWqoZupZ5RZ4cLMXAF9sn9/Vc013lNBU8Nl6G1xMwYWsgb40RxpWu2yh7In50Z9eAYmKUz1wImfR+0B9vbIhNnD0G/uI03VWCUY0DAcjK8gq2X2xEzCkZgtdgZ2Dcys9GHH11gN6sX7Cq+IthD+13m7C/pjPQSA4KSs/ldYMviPsuQ6PtrLecNDCImZcJTSzMp4DZDkz7VLkae5thmAFi1PGzuFXlUA=
    username: AgAUtV+IVxBEmQ0bvX1SDnf6moPmZPoWC2kZ0hczJ7yXRzIW3P4+6qOA5r6CefZcaHXDcBt5wh/9IFIWpf5kx7Wr6u9lOQBHYWLn2KmhqRNvSO1yaLsTDoddFKGNNywPxnC8nBWw7ivRCb0MeR/u1YCQB34kw5CoiJCp6VhdLyeqCEgSE2gNytt5cjqHag0tCAYuQRCqi3pXYXfJDS97LxQKnqxB/MuAJbQXg/UZm/9Cp7wCjYfI0saUpi6A1KejsDqUjj6Et/e2lDHV35j56X2F/+Wt//w0KgkVFjC2AwZ5lgqNHOPs9Vz0xjbvD+3qDqOz2rvPrbOtybbhu1g61dkd3JJtS5BLgJC/BqilGowabOOCVq1bgx0HBo4iIrtyE4/12E8wliqrORKCNqgpAoDHJ5EhL/idt2AHkU2CiYVZeUFawKnHWbqG9aLzHO1E+Z2qlbDRUz9MPV++Mh3bR2WCZV+GZ99P/o7lAUu0eqL7XaxxlreAEV2dBs+CH/EwMJkQ7OFoEGigNC4gHCSwG97+Drlv/zxo8cYxyRgMVDVYWlvIFa0J21CAGocLDpBsMSaIF07Q/Rk5MKPDDakvpSQjGXPK5MNUMXeIJD2S3Sl8VNIIQJ7ELsOc06xnb6UkGXlAlJ+li/zRjCF5S08bh2ePBs/U+s7y4zRpSVEi3NrtHrvXdG2nM91k0Sm216SjUVlWdoT0D6Frr7F5
  template:
    metadata:
      creationTimestamp: null
      name: github-bitwarden-token
      namespace: bitwarden
    type: Opaque
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: bitwarden
  namespace: bitwarden
spec:
  url: https://github.com/Notliam99/bitwarden-manifests.git
  interval: 12h
  secretRef:
    name: github-bitwarden-token
  ref:
    branch: main
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: bitwarden
  namespace: bitwarden
spec:
  interval: 12h
  prune: true
  sourceRef:
    kind: GitRepository
    name: bitwarden
  path: .
