apiVersion: v1
kind: Namespace
metadata:
  name: bitwarden
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: github-bitwarden-token
  namespace: bitwarden
spec:
  encryptedData:
    bearerToken: AgAJiJYpTd0II4661C8QUZf5cszYmnVz7uCjdXv6ctTe2ek7PLdv0iaOVq5SETt6v49MNUtwY0Qz4/Azwe4OV63K4Qh6cgh53n3gRm3dyrEwdEL37OvFenN0kZ4XWIAsLCyH1k2TI9hoyqPHboRBIRRxywTLHZIyLQ4oXAYe84dw0h8lQ6ek9gIWeXtY2q0JGwglKIl+145vaFviMafd5+yFGX2OEIceL6VWK5axkIEGPDyMCtriLFClM7rdejBsFTVLlFsDkUZ2jk3dtbJW9rL0VIsaP15qcivtdgfhKcZ1nJ/0uxrhY3x8/HLW7z4YBvWCepjV/HZTEwKqCwQ8wOLPi62f4xRjNjfW1oMHT+qaVanPXzGa+zsStJbQt7cnkw2gXH3aufC2hiqdOxZTmdu6iKsi5dJcibWlEToA2bPxdtd/oQP8ZOiFLuxSqaxg0oRqt3Rn4sYmgyYKsHWl5wz/NMbo5woyN3Xv01Pyg5NCviir2JXRWQt7bvVdAVY61TCqe0IRIJrvYG+PopzvG1iwo7EsNpLDqVp4PHAscxs0oS4qUvzeS3Voq/FK6iIy4h/ohpNDppLYlf6UMLloLm6/wdtYpVZ65GzYXWmPpeV1oKNfI+/JJjJQgiGeq3mjhpAddC+kon+ieYYV9R+yLddUnG2cccqz/34qfP5Vi2TsFhRbHbb8S3ZpX7v2PBGjUW5LBcAQfkEp49981VaO7tn9s/w4B35JneRu8Bk7ANDrf0KM30ipOSdsww==
  template:
    metadata:
      creationTimestamp: null
      name: github-bitwarden-token
      namespace: bitwarden
    type: Opaque
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: bitwarden
  namespace: bitwarden
spec:
  url: https://github.com/Notliam99/bitwarden-manifests.git
  interval: 2h
  secretRef:
    name: github-bitwarden-token
  ref:
    branch: main
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: bitwarden
  namespace: bitwarden
spec:
  interval: 1h
  prune: true
  sourceRef:
    kind: GitRepository
    name: bitwarden
  path: .
