apiVersion: v1
kind: Namespace
metadata:
  name: bitwarden
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: github-bitwarden-token
  namespace: bitwarden
spec:
  encryptedData:
    bearerToken: AgCpjQ90m650x2DuTsfnQf3OQTTvveB3CSkoB72v4vQOX47h86npp8pY1vgDMKYrNHV68ysR2Mc1Ii7s+zNJYJUBwYu3m5A8J6Tfk+rE3KIHSln5TPzYSO5jiDbX1ftEonprQvA+MK03/90oXrRz/++VSnP1HijhqCrSpMo5rEpG+NeS0QZa804wyxBTNHnZVcbFfVtl+jNp9OLpeJuWLA85l/Euqxgb0KwGjrMNBjGTaZfbN3D7c9f6kvJ0MLePxo+1HaaDj9w9k11x3M+PAEYRBfAD9/E8rQpWw5LiQZFR+7tuwZ2LKyLZ5WgNcTE52ebR4DWCkI4UNqkNgbSVRiPUqBqOIw4MJ3MCULTqghZptW2+nFcOr6gEfVqESqauX2aBCbVHjmx/06BHQ6AavyrFOCdCuBs9AtFxISZzq5DSdDm8p6mn+/MuJxfi35nP20Y/GKV5S1iDxfM/zGXnangrMPBe+vPRhZKZAoNXkTjK4/SOokZ5ZEnTog2SpCrJ/tY9YBHFIQbYvWr6YijKEiBadmHpiTqlVsskuENOCZ7lprjxnY4RoMzparbhzFDHxh1CmiZp13IhaoWSXAgr1+byu9kUX9OA4eTDMSovrWoYfIfjqsxxSezTUGZ4ghz9qakxd5sDr2PdPiCK789BGh26nMQ0AvRQaOIngxeXN15sJ8id4k5QxU/GxkVVWgwZ2UCP18UyiUrgJGm3tPEn1cBd9FNjkDLiuMD7Ba/kRrcZnaMFwSjIQexK
  template:
    metadata:
      creationTimestamp: null
      name: github-bitwarden-token
      namespace: bitwarden
    type: Opaque
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: bitwarden
  namespace: bitwarden
spec:
  url: https://github.com/Notliam99/bitwarden-manifests
  interval: 2h
  secretRef:
    name: github-bitwarden-token
  ref:
    branch: main
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: bitwarden
  namespace: bitwarden
spec:
  interval: 1h
  prune: true
  sourceRef:
    kind: GitRepository
    name: bitwarden
  path: .
