apiVersion: v1
kind: Namespace
metadata:
  name: nzdev-org-homepage
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: homepage-github-token
  namespace: nzdev-org-homepage
spec:
  encryptedData:
    identity: AgCiL9uph2SwKsdlnyLNPLYy0Ei6xABgdvoDpPXXRbsvgKVLA/+ZOaLio+GDICJGFf6m7hknMmkTEEFlIIIeRbJGz2835BSWdSN+Biti7ms7yZf/hBLfMM80YvgrxfPnb/Hqz5eqrwRITNOvz8cFKoMFVF5Em6UQOTYnRbgivTjai2b1WepaNtet0q1u+L19nRt44f2ckijIbyC1vh6ANRvWEKxIOd2ssuIAVi7F3R85FvR1rwpUUCgDgW38kzKu7R6f5pzdF1D6tGsZDQnr1C7PZrn9BOW72oMVFY8mPGzla99tU11BmF0A9Tbu44AA16+bR2EVQCHvY4OofT/TV99SCdC32a5+VJ/ta4W89tWH1zyltltChZ2cn0nZazCQWNVFWjfq2a7WztLq8HyaIRbRvfsssZeSOqCWiLdQDNRLmXATLQfx/ppA5iRxGD8ihn5qB1O131ngoD2DSJ8lKXaE2F1SWMRxSSwWrGV1p5dK2V813GSfXpfiRqhWKezT/q0d1Crq5cFtndeO+t91Bu/mToO/1jglVXYcor1loaIqWmZ4/aOiedveVjmNkWUy4HIY+cQZrAzAxy07lOGLEzLrv0xxJVPoXKIVEIpHYR5umz5EepIrl2LPf5isKxGYeKr6QFLNDkgre5RHoPAOT5kJi1R5GBpwWZGuwGAZxmOy+E3lBhIZm+FO1RQSFRR+JfdI1wWI4SbVMgzkbFbsyZPJBMB60XZ8aRGWSXyhpHsJ29clPS07eF15s5IYLHzz8cwsDFiJow4YZXwNE/31Mi/E+eewUEenOYULMp7uPg6ETn/nLKiuTOinx0m+eIckIGSG75R6CkNquEGLCs0Y73zjOW18E4v7sAtEmr2auG4azf/HZ5tvNW3C7Src8/zkJyQ0Out9TD9bXCGtxYhS/oj/8W5pfnCBV5j2YNmz7O3CtnzYbblfastdAAp6WTUHqYsMqwYDSq7A3Lmk7B5m2f7ONw/yVY8e29ePYueR65KobUUyK7CveTZyUOO886jewRrhM6iVKJIRkgl79vlYrYjUAMfv4Nt4VZvfNHuAEMJCGTWFZ4sTXGDPYVFrBZ10YhoIj4qIFq6x2PYUKSW0IBhYanjzs/8x9Esbylv1Mo90rR7XICTCxPWxnxqg5RbK7rAx9rKqYVVBqEcFUSvyxydqz97UA7345p7e55C8VovPo5BkOWysLXHO+pRamsbfMx/HX93Hd5SFqUzl7DmMTS64/Y1/yzUVHa6KDDE=
    known_hosts: AgCwdGbFjaWpP5C3f7/oG7jUrONukkZ0PF5yoCMeMlTvrT2JMApucwPBGO4/xz4NXb/St8PAoVA4qEHIk9fABAbzkTEN3pjgn91VqrS+uamgGdyqhciqOnqHlGbqHpzmWw732ybnCJOD0SY6xHq9hQiaelgCaIUqc8/fW3yiDZUIIOrjYJ/dOoujkyNGI5/2FGrBBzXjbU9wCP1mKX+pF4zWdv6hCU/ILZeU9zH2mLDYU4nR0JDSS++uh1DcS3HjBhYti2Aoe9mFlfUtjnLNQJ4ZxK6gy2SwhmYHZd+P91B0uMUFpEvKKNVB4LFMS0VnNcLkY7mm+mxvB9vB5/R0XzpVLg7BfS5V2gRg0a1HEjQqwqlmuO1TxpZ8Ax+wNuoSO0LonV8BrPpoZswiYzcHwOknckxErJ08yobUNMcp8Hcej0WWNHxbPiwKca23YE4vCISKOtcRRdphlNeyfXOfUpFAgjycel/jUPUkBZgLjw7+vgLhN7W8QEPATrfM59CF8uPrFSNtDrtpcS0Kteor7bUvvX9ZfA+oYEnPBGScv2Ki6M/GYxPiLUIeGgvhcLn24Xu6DmF3ekF+ZHSB/qRjJ+NV7Od0kJSU7iKvPLxikhofCre4mxwevs5uyC9dbu0C7N4Re6m8jpRbVvtk/99KHllka9AxeEwOR9yQKH2/aKzmyMEk+rhuosLlRDhnCG1fqgKqiQH+syqkprIQH6oVq1KhQFDwMUQ2uEfzl7dxZVkfp7mIpLV4D4tM2tRopUilEsAdWq6yXfX1VkDVHvLF9CaYaVqSm5fYpQ64jaxaXfchCaaAuXkBcN5hR39Xg3KZPS1Wi7SEiEWdEWCDyfZmUrBGTMnlhi9bsg74MkA3DdrRbp+Tlfz5wL+oIhLDnbjKOlYerxCLTvWZNPFRYGusUI/MS2zfYDSGEwugP8oQeqdvf2UrXCnJhzJjSbH9OEBFV4IrD3gv1xhm0L3fDeAW+u9AYGWgwAxiplNJWwjhLgz7XVPtExTzEavRMUb8cP3cz+eZtrJcQgTUnriRjVoHHdlsmiurcekk3EoYd0IRAQjrohQVzAfPDV4WKXbGYE/LA+rJ15sIy3eqIEbBUjj2ghMFKzm7CR3Dd0hUw+wjsA+o342kBD7lVTY2sQwIEFrGch19pqbwwpRvjy4BaryT2gHOrHjYrhZlRtiVp80+8l4nn8ZaqcHsW7PdMX4jbcHBmlLcYuTMcf7pp6lhiRVZFZXMAQibAuNmCQhN6otV//IAYWvt5hy9JhqeVsAy9WwFkCK6fpEshve9HG5h+DIFvs4OnOcnxWyKnaWAbdDDSZNJpHcYT02LaLbcd9tEhyzi47rYNt4l592KMQ02dgZOLyb1d13YSxo4ahYEjMSbFhnL6T9qADgKYR+9GuRDSLKQIGdNDwPwWwi2voEEOclxQK/3AXfAXe8MpKMs2KfHVXlS8Na3sf79/9l7UGB8Hs1Nyup74RBk3P1hS7ZUAeApye9/1sn5jE+tcUuZM/27aMOGIdrKh6VmWvcdaHEzxdeYeUditDh2bL/V6luMZV3XCZh6m+O8kLKBZyCYBbcx1l8ogEns0AqH06Zcxtw59rkHsntxtAGopl2Uk4mm+7CE9JMPxaeHMNzJIn8DxGHpGzesKEd7ELVnn5HciA3VIHx01IfJdclgIkwkb1FwEFSNCeMbZzaIpIv+iBxMmGaLQHC/uXRJ38dDMpaxRaXLbP0XyzUgYHzFVo8kdcUzMcEXFO8LMrcEfPLRddlvVN4cwjJVILEEx6ba8Cmj3r+5r/ipiCDM7qHuxbtHtysJaEI=
  template:
    metadata:
      creationTimestamp: null
      name: homepage-github-token
      namespace: nzdev-org-homepage
    type: Opaque
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: nzdev-org-homepage
  namespace: nzdev-org-homepage
spec:
  url: ssh://git@github.com:Notliam99/nzdev-org.git
  interval: 12h
  secretRef:
    name: homepage-github-token
  ref:
    branch: main
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: nzdev-org-homepage
  namespace: nzdev-org-homepage
spec:
  interval: 12h
  prune: true
  sourceRef:
    kind: GitRepository
    name: nzdev-org-homepage
  path: ./deploy
