apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: traefik
  namespace: traefik-system
spec:
  chart:
    spec:
      chart: traefik
      sourceRef:
        kind: HelmRepository
        name: traefik
      version: 36.1.0
  values:
    globalArguments:
      - "--global.sendanonymoususage=false"
      - "--global.checknewversion=false"
    ports:
      # Internal Traefik Services
      traefik:
        port: 8080
        expose:
          default: true
        exposedPort: 8080
        protocol: TCP
      # External [HTTP] Services
      web:
        port: 8000
        expose:
          default: true
        exposedPort: 80
        protocol: TCP
      # External [HTTP(s)] Services
      websecure:
        port: 8443
        expose:
          default: true
        exposedPort: 443
        protocol: TCP

    service:
      enabled: true
      type: LoadBalancer
      annotations: {}
      labels: {}
      spec:
        loadBalancerIP: 192.168.50.10 # this should be an IP in the MetalLB range
      loadBalancerSourceRanges: []
      externalIPs: []

  interval: 1m0s
