apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  namespace: notes
  name: notes-ingress
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: web, websecure
spec:
  tls:
    - hosts:
        - nzdev.org
      secretName: nzdev-org-tls
  rules:
  - host: nzdev.org
    https:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: notes-service
            port:
              number: 80
