---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloudflare-token
  namespace: cert-manager
spec:
  encryptedData:
    cloudflare-token: AgCtM5GdaY0do0qRl+yhajn+N0YauKIrD8gt0q+Ikg/MHoaDv2GcOApRh78HKb3WgdtBrqg6Bv8iYknqSq8lqAKu+wu98/zuEyGv8TvcC6NQdyPNEEeBZp7U7Avr0rsbHbFKJVkqBNtNYXC3j9AgEXJBRJAs+YP5C7j/2JfMqDdZjIflltMW/3ff4kg7qKCazcpxWQpElsLNQWdWlGZqsIPTYcZ4h+DhJiGiNm0FOMYo+YRz3viOO4l6eFzd3ahGW/EhdyATzgS9menN6UCZ4rksqX5Itw9bCLP2SVWW5Y1jlEGBvdqhQTgqQepwyyGytH+Ce8jIUfPPniryqbCcep8N5zpDtrT+tHEQOLh29PiB3gG2LL2E14VbEI7r+Qjokb5RVXq4DP38mNgCuyn2ijC0gd4QFiF/yYWsiF3Q06R4vcA9wQy/hGxfVMp+6PuDVaAupWQQdo/fKZGYOfm9BBNiwCmfqy17UdiU0YnK6xyboT/CfIF9rta4DXxRvh927nQd+SuZjqlfuSOU4l3uPVzQgaeM7vTbDxFZ5dltxp01L/tPIEtEbs9lXlD1HB+j2XDvkZYYfsxUmxLhmHaM06jTK/bAHtZ8/jmxq3/7qeFqjYsYGD/+WJMypajxkJheQ8G3tzbKmsUxpPId7e0U1LDs2le42s1HD37GN8XgjyLdw3xDoVeJPgJmhIb95Cd0GVUz7BAAbNQiHuOrKwS6oKrW9iTiQbpFgWTY6IdOfpiI7VaPiwBw34hr
  template:
    metadata:
      creationTimestamp: null
      name: cloudflare-token
      namespace: cert-manager
    type: Opaque
