apiVersion: v1
kind: Namespace
metadata:
  name: sealed-secrets
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: sealed-secrets
  namespace: flux-system
spec:
  interval: 1h0m0s
  url: https://bitnami-labs.github.io/sealed-secrets
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: sealed-secrets-1
  namespace: flux-system
spec:
  chart:
    spec:
      chart: sealed-secrets
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: sealed-secrets
      version: '>=2.5.15'
  values:
    ingress:
      enabled: true
      hostname: sealed.nzdev.org
      path: /v1/cert.pem
      annotations:
        traefik.ingress.kubernetes.io/router.entrypoints: websecure
  install:
    crds: Create
  interval: 1m
  releaseName: sealed-secrets-controller-1
  targetNamespace: flux-system
  upgrade:
    crds: CreateReplace
  driftDetection:
    mode: enabled
