apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-token
  namespace: cert-manager
type: Opaque
stringData:
  cloudflare-token: jB35zILBObfOpbGBAb2tP2VGMc3jawLSUq-wXX5T
---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: cert-issuer
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: cert.issuer@nzdev.org
    privateKeySecretRef:
      name: letsencrypt-cert
    solvers:
      - dns01:
          cloudflare:
            email: l.tietjens@hotmail.com
            apiTokenSecretRef:
              name: cloudflare-token
              key: cloudflare-token
        selector:
          dnsZones:
            - "nzdev.org"
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: nzdev-org
  namespace: cert-manager
spec:
  secretName: nzdev-org-tls
  issuerRef:
    name: cert-issuer
    kind: ClusterIssuer
  commonName: "*.nzdev.org"
  dnsNames:
  - "nzdev.org"
  - "*.nzdev.org"
---
apiVersion: traefik.io/v1alpha1
kind: TLSStore
metadata:
  name: default-cert
  namespace: cert-manager

spec:
  defaultCertificate:
    secretName: nzdev-org-tls

