apiVersion: v1
kind: Namespace
metadata:
  name: sealed-secret-system
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: sealed-secret
  namespace: sealed-secret-system
spec:
  chart:
    spec:
      chart: sealed-secrets
      sourceRef:
        kind: HelmRepository
        name: sealed-secrets
      version: 2.5.15
  values:
    ingress:
      enabled: true
      hostname: sealed.nzdev.org
      path: /
      annotations: {
        traefik.ingress.kubernetes.io/router.entrypoints: web, websecure
      }

  interval: 1m0s
